version: '3.4'

services:
  retrospective-identity:
    image: ${DOCKER_REGISTRY-}retrospective-identity:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Retrospective.Infrastructure.Identity/Dockerfile
    ports:
        - "5000:80"
    depends_on:
      - sql-server
      - seq

  retrospective-api:
    image: ${DOCKER_REGISTRY-}retrospective-api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Retrospective.API/Dockerfile
    ports:
        - "5001:80"
    depends_on:
      - sql-server
      - seq
      - retrospective-identity

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./sql-data:/data      

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./seq-data:/data
