// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retrospective.Infrastructure.Persistence;

namespace Retrospective.Infrastructure.Migrations
{
    [DbContext(typeof(SprintContext))]
    partial class SprintContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.6.20312.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Retrospective.Domain.AggregatesModel.SprintAggregate.Item", b =>
                {
                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SprintItemId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("SprintItemId");

                    b.ToTable("Items","Retrospective");
                });

            modelBuilder.Entity("Retrospective.Domain.AggregatesModel.SprintAggregate.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sprints","Retrospective");
                });

            modelBuilder.Entity("Retrospective.Domain.AggregatesModel.SprintAggregate.SprintItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SprintId")
                        .HasColumnType("int");

                    b.Property<int>("SprintItemType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SprintId");

                    b.ToTable("SprintItems","Retrospective");
                });

            modelBuilder.Entity("Retrospective.Domain.AggregatesModel.SprintAggregate.Item", b =>
                {
                    b.HasOne("Retrospective.Domain.AggregatesModel.SprintAggregate.SprintItem", null)
                        .WithMany()
                        .HasForeignKey("SprintItemId");
                });

            modelBuilder.Entity("Retrospective.Domain.AggregatesModel.SprintAggregate.SprintItem", b =>
                {
                    b.HasOne("Retrospective.Domain.AggregatesModel.SprintAggregate.Sprint", null)
                        .WithMany("SprintItems")
                        .HasForeignKey("SprintId");
                });
#pragma warning restore 612, 618
        }
    }
}
